### ISSUE TITLE
Checklist hoàn thành tiến độ

### ISSUE THREAD

**Issue by zz2zz22** [zz2zz22/WeebChat-mobile#3]
- [ ] Send hình ảnh
- [ ] Send file pdf
- [ ] Send file MS word
- [ ] Xóa đoạn chat
- [ ] Chat nhóm
- [ ] Tìm đoạn chat bất kỳ
- [ ] Hiển thị thông báo tin nhắn mới
- [ ] Hiển thị số tin nhắn chưa đọc
- [ ] Hiển thị tin nhắn đã đọc xem hay chưa
- [ ] IPA

**Comment by zz2zz22** [comment]
> API hiển thị thông báo tin nhắn bị xung đột
